function base64Img2Blob(code){var parts=code.split(';base64,');var contentType=parts[0].split(':')[1];var raw=window.atob(parts[1]);var rawLength=raw.length;var uInt8Array=new Uint8Array(rawLength);for(var i=0;i<rawLength;++i){uInt8Array[i]=raw.charCodeAt(i);}
    return new Blob([uInt8Array],{type:contentType});}
function showErrorBox(msg){$("body").append("<div class='alert alert-danger alert-box' id='errorbox'></div>");var errorbox=$('#errorbox');errorbox.text(msg);errorbox.fadeIn();setTimeout(function(){errorbox.fadeOut();},3000)}
function showSuccessBox(msg){$("body").append("<div class='alert alert-success alert-box' id='successbox'></div>");var successbox=$('#successbox');successbox.text(msg);successbox.fadeIn();setTimeout(function(){successbox.fadeOut();},2000)}
function copyStr(str){var oInput=document.createElement('textarea');oInput.style.position='absolute';oInput.style.opacity='0';oInput.value=str;document.body.appendChild(oInput);oInput.select();document.execCommand("Copy");document.body.removeChild(oInput);}
$(function(){$('#toolboxMenu').hover(function(){$('#toolboxMenuUL').show();},function(){$('#toolboxMenuUL').hide();});$('#search').submit(function(){if($('#keyword').val()==""){return false;}});var haveShowAd=false;var pcFlag=$(window).width()>800?true:false;var curHour=new Date().getHours();var curDay=new Date().getDay();var txy="https://cloud.tencent.com/act/cps/redirect?redirect=1074&cps_key=edb15096bfff75effaaa8c8bb66138bd&from=console";function openAd(url,self){localStorage.setItem("clickedAdTime",new Date().getTime());if(self==true){window.open(url,'_self');}else{window.open(url);}}
    function haveClickedAd(){var adDays=7*24*60*60*1000;if(localStorage.getItem("clickedAdTime")==null||(new Date().getTime()-localStorage.getItem("clickedAdTime"))>adDays){return false;}
        return true;}
    if(window.location.pathname.indexOf("/api/")==0){if(haveShowAd==false&&pcFlag==true&&haveClickedAd()==false){haveShowAd=true;$(".navbar-fixed-top").prepend('<div id="topAd"><div id="closeTopAd">关闭</div></div>');$("#topAd").css("height","100px");$("#topAd").css("background","url(../../img/common/tencent_ms_1200_90.png)");$("#topAd").css("background-size","100% 100%");$('#topAd').click(function(e){openAd(txy,false)});$('#closeTopAd').click(function(e){$('#topAd').hide();if(haveClickedAd()==true){e.preventDefault();return false;}});}}
    $("#contentRight").prepend('<div id="rightImgAd"></div>');$("#rightImgAd").css("height","280px");$("#rightImgAd").css("background","url(../../img/common/tencent_ms_280_280_1111.png)");$("#rightImgAd").css("background-size","100% 100%");$('#rightImgAd').click(function(e){openAd(txy,false);});$(window).scroll(function(){var curHour=new Date().getHours();if(haveShowAd==false){haveShowAd=true;if(window.location.pathname=="/"){return false;}
        setTimeout(function(){if(haveClickedAd()==false){var popHtml='<div id="popAd"><div id="closePopAd">关闭</div></div>';$(".navbar-fixed-top").prepend(popHtml);if(pcFlag==false){$("#popAd").css("width","280px");$("#popAd").css("height","280px");$("#popAd").css("background","url(../../img/common/tencent_ms_280_280_1111.png)");$("#popAd").css("background-size","100% 100%");$('#popAd').click(function(e){openAd(txy,false)});}else{$("#popAd").css("width","480px");$("#popAd").css("height","300px");$("#popAd").css("background","url(../../img/common/tencent_ms_480_300_1111.png)");$('#popAd').click(function(e){openAd(txy,false)});}
            $('#closePopAd').click(function(e){$('#popAd').hide();if(haveClickedAd()==true){e.preventDefault();return false;}});}},6000);if(pcFlag==true&&window.location.pathname.indexOf("/blog/")==0){setTimeout(function(){if(haveClickedAd()==false){openAd(txy,true);}},122000);}}
        var scrollHeight=$(document).height();var scrollTop=$(window).scrollTop();scrollTop>100?$(".back-top").slideDown(300).css("display","block"):$(".back-top").slideUp(300);});$('.back-top').click(function(e){e.preventDefault();$('html,body').animate({scrollTop:0});});});$(function(){var url=window.location.href;url=url.replace(/(\/+)$/g,"");var arrUrl=url.split("/");if(arrUrl.length==3){var lastViews=getHistory(12);var lastUsedHtml='';lastViews.forEach(function(obj){lastUsedHtml=lastUsedHtml+'<a class="col-lg-2 col-md-3 col-sm-4 col-xs-6 tool_link_title" href="'+obj.href+'" target="_blank" title="'+obj.title+'">'+obj.title+'</a>';});if(lastUsedHtml!=''){lastUsedHtml='<div id="toolUsedDiv"><div class="row"><h2 class="tool_kind_title">最近使用</h2><a class="btn glyphicon glyphicon-trash text-muted" title="清除使用记录" onclick="removeHistory()"></a></div><div class="row">'+lastUsedHtml+"</div></div>";$(".tool_box").prepend(lastUsedHtml);}}
    if(arrUrl.length==4&&arrUrl[3]!=""&&arrUrl[3]!="api"&&arrUrl[3]!="page"&&arrUrl[3]!="software"&&arrUrl[3]!="pic"&&arrUrl[3]!="blog"&&arrUrl[3]!="library"&&arrUrl[3]!="map"&&arrUrl[3]!="s"&&arrUrl[3].indexOf("s?")==-1){var urlName=arrUrl[3];var title=document.title;title=title.substring(0,title.length-6);if(title!=""){if(haveViewed(urlName)==false){$.getJSON("/updateLikenum.json?url="+urlName+"&type=toolbox");}
        var saveID=urlName+"@#@"+title+"@#@"+url;saveHistory(saveID);}}else if((arrUrl.length==5&&arrUrl[3]=="blog"&&!isNaN(arrUrl[4]))||(arrUrl.length==6&&arrUrl[3].indexOf("lang-")==0&&arrUrl[4]=="blog"&&!isNaN(arrUrl[5]))){var blogId=arrUrl.length==5?arrUrl[4]:arrUrl[5];var title=document.title;title=title.substring(0,title.length-11);if(title!=""){if(haveViewed(blogId)==false){$.getJSON("/updateLikenum.json?url="+blogId+"&type=blog");}
        var saveID=blogId+"@#@"+title+"@#@"+url;saveHistory(saveID);}}});var countNum=22;var historyLS="viewHistory";var hisSplitFlg=";#;";function removeHistory(){localStorage.removeItem(historyLS);$("#toolUsedDiv").remove();}
function saveHistory(saveID){var historyp;if(saveID==null||saveID==""){return;}
    if(localStorage.getItem(historyLS)==null){localStorage.setItem(historyLS,saveID);return;}else{historyp=localStorage.getItem(historyLS);};var pArray=historyp.split(hisSplitFlg);historyp=saveID;var count=0;for(var i=0;i<pArray.length;i++){if(pArray[i]!=saveID){historyp=historyp+hisSplitFlg+pArray[i];count++;if(count==countNum-1){break;}}}
    localStorage.setItem(historyLS,historyp);}
function getHistory(size){var historyp=localStorage.getItem(historyLS);if(historyp==null||historyp==""||historyp=="null"){return[];}
    var contents=[];var pArray=historyp.split(hisSplitFlg);for(var i=0;(i<size&&i<pArray.length);i++){if(pArray[i]!=""&&pArray[i]!="null"){var arr=pArray[i].split("@#@");if(typeof arr[0]!="undefined"&&arr[0]!=null&&arr[0]!="null"&&arr[0]!=""&&arr[0]!=" "&&arr[0]!="undefined"&&typeof arr[1]!="undefined"&&arr[1]!=null&&arr[1]!="null"&&arr[1]!=""&&arr[1]!=" "&&arr[1]!="undefined"&&typeof arr[2]!="undefined"&&arr[2]!=null&&arr[2]!="null"&&arr[2]!=""&&arr[2]!=" "&&arr[2]!="undefined"){contents.push({id:arr[0],title:arr[1],href:arr[2]});}}}
    return contents;}
function haveViewed(contentId){var historyp=localStorage.getItem(historyLS);if(historyp==null||historyp==""||historyp=="null"){return false;}
    if(historyp.indexOf(contentId)>=0){return true;}
    return false;}
// (function(){var bp=document.createElement('script');var curProtocol=window.location.protocol.split(':')[0];if(curProtocol==='https'){bp.src='https://zz.bdstatic.com/linksubmit/push.js';}
// else{bp.src='http://push.zhanzhang.baidu.com/push.js';}
//     var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(bp,s);})();var _hmt=_hmt||[];(function(){var hm=document.createElement("script");hm.src="https://hm.baidu.com/hm.js?9cc074900445f1842472986022b3fd60";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(hm,s);})();